name: 'Batch update source code'
description: 'Batch update source code of the specified tag to the personal repo'
inputs:
  github_token:
    description: Base64 encoded Personal Access Token
    required: true
  source_repo:
    description: 'source_repo'
    required: true
  source_tag:
    description: 'source_tag'
    required: true
  source_branch:
    description: 'source_branch'
    required: true
  target_repo:
    description: 'target_repo'
    required: true
runs:
  using: 'node16'
  main: 'index.js'
